repos:
-   repo: https://github.com/ViktoryiaPazniak/LoadData
    rev: v2.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-json
    -   id: end-of-file-fixer
    -   id: name-tests-test
    -   id: requirements-txt-fixer